### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by johneakin** [bordalix/scrape_doublespend_cash#2]
I flicked through a lot of the successful double spends and all that I could see happen within 1 second of the original.

This would suggest that the below is false
'It looks like ¼ of the miners are breaking ranks and are not following the “first-seen-safe” rule, exactly as the tragedy of the commons theory predicts.'

and instead the second transaction is just propagating faster?

**Comment by bordalix** [comment]
Actually, there are a lot of factors to consider as the cause of the double spends.
Peter R. Rizun has made a terrific study that you can watch here:
https://twitter.com/PeterRizun/status/1052290005232570368
